#!/usr/bin/env bash
# Installing Nginx Web Server

sudo apt-get update -y

sudo apt-get install nginx -y

sudo ufw allow 'Nginx HTTP'

sudo chown -R $USER:$USER /var/www

sudo chmod -R 755 /var/www

echo "Hello World!" | sudo tee /var/www/html/index.html

service nginx start
