#!/usr/bin/env bash
#configure Nginx server to redirect to another page
# automate installation and set up of nginx web server, redirection
# and custom error messages

sudo apt-get update 

sudo apt-get install nginx -y nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.google.com;\n\t}"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
