#!/usr/bin/env bash
# customizing 404 page

sudo apt-get update

sudo apt-get install nginx -y nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.google.com;\n\t}"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

#creating a 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

string_for_replacement="server_name _;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

#restart nginx after implementing changes

sudo service nginx restart
