#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
#	displays To infinity and beyond indefinitely
#	displays I hate the kill command when receiving a SIGTERM signal
#	displays Y U no love me?! when receiving a SIGINT signal
#	deletes the file /var/run/myscript.pid and terminates itself
#	when receiving a SIGQUIT or SIGTERM signal

terminate() {
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while :
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"; terminate' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'terminate' SIGQUIT
done
