#!/usr/bin/env bash
# uses ssh to connect to server

ssh -i ~/.ssh/id_rsa ubuntu@34.224.94.228
# server-01 login commands

# setting up the ssh-agent
eval $("ssh-agent")

# path to identityFile
ssh-add ~/.ssh/id_rsa

# username and IP
ssh ubuntu@34.224.94.228
